[package]
name = "revup"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
dotenv = "0.15.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json="1.0.59"
